import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dbSetupRouter from "./db-setup";
import productsRouter from "./products";
import categoriesRouter from "./categories";
import bannersRouter from "./banners";
import quotesRouter from "./quotes";
import contactRouter from "./contact";
import blogRouter from "./blog";
import pagesRouter from "./pages";
import adminRouter from "./admin";
import seoRouter from "./seo";
import usersRouter from "./users";
import mediaRouter from "./media";
import templatesRouter from "./templates";
import customersRouter from "./customers";
import ordersRouter from "./orders";
import invoicesRouter from "./invoices";
import portalRouter from "./portal";
import importWpRouter from "./import-wp";
import exportRouter from "./export";
import followUpsRouter from "./follow-ups";
import securityRouter from "./security";
import databaseRouter from "./database";
import chatRouter from "./chat";
import resolveRouter from "./resolve";
import menusRouter from "./menus";
import supportTicketsRouter from "./support-tickets";
import formsRouter from "./forms";
import auditRouter from "./audit";
import contentRevisionsRouter from "./content-revisions";
import monitoringRouter from "./monitoring";
import capabilitiesRouter from "./capabilities";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/db-setup", dbSetupRouter);
router.use(seoRouter);
router.use(resolveRouter);
router.use(menusRouter);
router.use(supportTicketsRouter);
router.use(formsRouter);
router.use(auditRouter);
router.use(contentRevisionsRouter);
router.use(monitoringRouter);
router.use(capabilitiesRouter);
router.use(productsRouter);
router.use(categoriesRouter);
router.use(bannersRouter);
router.use(quotesRouter);
router.use(contactRouter);
router.use(blogRouter);
router.use(pagesRouter);
router.use(adminRouter);
router.use(usersRouter);
router.use(mediaRouter);
router.use(templatesRouter);
router.use(customersRouter);
router.use(ordersRouter);
router.use(invoicesRouter);
router.use(portalRouter);
router.use(importWpRouter);
router.use(exportRouter);
router.use(followUpsRouter);
router.use(securityRouter);
router.use(databaseRouter);
router.use(chatRouter);

export default router;
